### ISSUE TITLE
Bug: PSO: incorrect velocity calculation after simplification update

### ISSUE THREAD

**Issue by wlfbck** [SebastianNiemann/Mantella#212]
With the removal of the neighbourhood topology a slight mistake was made:
`const arma::Col<double>& velocity =
          maximalAcceleration_ * arma::randu<arma::Col<double>>(numberOfDimensions_) % velocities_.col(activeParticleIndex_) + randomNeighbour(attractionCenter, 0, arma::norm(attractionCenter));`
was simplified into
`const arma::vec& velocity = randomNeighbour(getMaximalAcceleration() * mant::randu(numberOfDimensions_) % velocities_.col(n), 0, arma::norm(attractionCenter));`
which apparently is wrong (not even 30% success rate on sphere 5D vs >99% with old codeline). I suspect it's because randomNeighbour(...) is supposed to be added ontop of the calculation there.

**Comment by wlfbck** [comment]
This bug still applies, despite something being wrong with mant::randu right now.

**Comment by SebastianNiemann** [comment]
Thanks for the catch! The problem seems to be the missing `attractionCenter` als Position in the second case.

m = `maximalAcceleration_`
**u** = `arma::randu<arma::Col<double>>(numberOfDimensions_)`
**v** = `velocities_.col(activeParticleIndex_)`
**a** = `attractionCenter`
`.*`= element-wise multiplication

First case: m * **u** .* **v** + `randomNeighbour`(**a**, 0, |**a**|)
Erroneous second case: `randomNeighbour`(m * **u** .* **v**, 0, |**a**|)
Corrected second case: `randomNeighbour`(m * **u** .* **v** + **a**, 0, |**a**|)

However, I think the first case is more focused on the calculation this was derived from.

**Comment by SebastianNiemann** [comment]
This was also resolved by #214
